### ISSUE TITLE
EcoTyper does not handle spaces in path names

### ISSUE THREAD

**Issue by kaizen89** [digitalcytometry/ecotyper#34]
I have a dropbox business account and I'm trying to run EcoTyper example tutorial but I get an error due to the dropbox root folder name containing a space, even when I put the absolute paths between quotes.

**Comment by BALuca** [comment]
Hi, 

Thank you for reporting the issue. The error is likely produced by a bug introduced at the previous commit. The latest version should fix it. Please let us know if you encounter any issues.

Best,
The EcoTyper team

**Comment by kaizen89** [comment]
Unfortunately the issue still persists.
I tried to input the absolute path name and escaping the space and ( ) but I still get an error
```
salmon@salmon5820:/mnt/sda3/Dropbox (U932)/myDropbox/Lab/programs/Github_tools/ecotyper$ Rscript EcoTyper_recovery_bulk.R -d Carcinoma -m "/mnt/sda3/Dropbox (U932)/myDropbox/Lab/programs/Github_tools/ecotyper/example_data/bulk_lung_data.txt" -a "/mnt/sda3/Dropbox (U932)/myDropbox/Lab/programs/Github_tools/ecotyper/example_data/bulk_lung_annotation.txt" -c Tissue -o RecoveryOutput
sh: 1: Syntax error: "(" unexpected
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Execution halted
salmon@salmon5820:/mnt/sda3/Dropbox (U932)/myDropbox/Lab/programs/Github_tools/ecotyper$ Rscript EcoTyper_recovery_bulk.R -d Carcinoma -m /mnt/sda3/Dropbox\ \(U932\)/myDropbox/Lab/programs/Github_tools/ecotyper/example_data/bulk_lung_data.txt -a "/mnt/sda3/Dropbox\ \(U932\)/myDropbox/Lab/programs/Github_tools/ecotyper/example_data/bulk_lung_annotation.txt" -c Tissue -o RecoveryOutput
Warning message:
In normalizePath(args$annotation) :
  path[1]="/mnt/sda3/Dropbox\ \(U932\)/myDropbox/Lab/programs/Github_tools/ecotyper/example_data/bulk_lung_annotation.txt": No such file or directory
Error: Error: Path to the input annotation file does not exist!
Execution halted
```

**Comment by BALuca** [comment]
Hello,

EcoTyper should be able to handle spaces in path names. Please let us know if you encounter any problems with it.

Best,
The EcoTyper team

**Comment by jentwa97** [comment]
I am having a similar issue. I set the path to my .txt file as both "data" and "path", but I keep getting "Error in path.expand(path) : invalid 'path' argument" when I try to run "input_mat = normalizePath(args$matrix)". Any suggestions?
